{
  "hash": "7ba0e9a07eb70da75a3ff9288b377faf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1 (Technical Report)\"\nauthor: \"Bui Tien Thanh\"\ndate: \"May 9, 2026\"\ndate-modified: \"last-modified\"\nexecute:\n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n## Overview\n\nThis assignment focuses on analyzing a real-world motor vehicle insurance portfolio dataset from a Spanish insurance company using visual analytics techniques.\n\n[**View Full Assignment Requirements**](requirements.qmd)\n\n### Quick Summary\n\n- **Data:** Motor insurance portfolio dataset (Spanish insurance company)\n- **Tasks:** Univariate and bivariate visual analytics\n- **Tools:** tidyverse, ggplot2 and extensions\n- **Due Date:** 24th May 2026, 11:59pm\n\n------------------------------------------------------------------------\n\n## Loading Packages\n\nWe load the following R packages using the pacman::p_load() function:\n\n- `tidyverse` for data manipulation and visualization\n- `ggplot` for data visualization\n- `readxl` for reading Excel, CSV files\n- `skimr` for data profiling\n- `patchwork` for preparing composite figure created using ggplot2\n- `ggstatsplot` for creating graphics with details from statistical tests included in the information-rich plots themselves\n- `ggdist` for visualizations of distributions and uncertainty\n- `ggridges` for ridgeline plots\n- `scales` for providing the internal scaling infrastructure used by ggplot2\n- `viridis` for providing colorblind-friendly, perceptually uniform color palettes\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, ggplot2, readxl, skimr, patchwork, ggstatsplot, ggdist, ggridges, scales, viridis)\n```\n:::\n\n\n## Data Preparation\n\n### Import Data\n\nThere are two files:\n\n- `Dataset of motor insurance portfolio.csv`: This is our main dataset\n- `Descriptive of variables.xlsx`: This is just the metadata\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_data <- read.csv(\n  \"../../data/Dataset of motor insurance portfolio.csv\",\n  sep = \";\",\n  dec = \".\"\n)\n```\n:::\n\n\n### Data Exploration\n\nQuickly take a look of our insurance dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(insurance_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,140\nColumns: 47\n$ insured_id                  <int> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <int> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <chr> \"COMP_E\", \"COMP_E\", \"COMP_E\", \"COMP_E\", \"C…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <chr> \"NB\", \"P\", \"P\", \"P\", \"NB\", \"P\", \"P\", \"NB\",…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <chr> \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G\", \"G…\n$ driver_age                  <int> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <int> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <int> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <chr> \"G\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D\", \"D…\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <int> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <chr> \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I\", \"I…\n$ circulation_area            <chr> \"U\", \"U\", \"U\", \"U\", \"R\", \"R\", \"R\", \"R\", \"R…\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <int> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <int> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <int> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <int> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(insurance_data)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |               |\n|:------------------------|:--------------|\n|Name                     |insurance_data |\n|Number of rows           |354140         |\n|Number of columns        |47             |\n|_______________________  |               |\n|Column type frequency:   |               |\n|character                |9              |\n|numeric                  |38             |\n|________________________ |               |\n|Group variables          |None           |\n\n\n**Variable type: character**\n\n|skim_variable     | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-----------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|policy_type       |         0|             1|   2|   6|     0|        5|          0|\n|policy_status     |         0|             1|   1|   1|     0|        2|          0|\n|business_type     |         0|             1|   1|   2|     0|        2|          0|\n|payment_frequency |         0|             1|   1|   1|     0|        3|          0|\n|bonus_score       |         0|             1|   1|   1|     0|        3|          0|\n|fuel_type         |      1287|             1|   1|   1|     0|        2|          0|\n|vehicle_brand     |         0|             1|   2|  12|     0|       68|          0|\n|municipality_type |         0|             1|   1|   2|     0|        3|          0|\n|circulation_area  |         0|             1|   1|   1|     0|        2|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable               | n_missing| complete_rate|     mean|       sd|      p0|      p25|      p50|       p75|      p100|hist  |\n|:---------------------------|---------:|-------------:|--------:|--------:|-------:|--------:|--------:|---------:|---------:|:-----|\n|insured_id                  |         0|             1| 76044.50| 51272.26|    1.00| 33342.00| 66840.00| 112949.00| 185678.00|▇▇▆▃▃ |\n|year                        |         0|             1|  2023.29|     0.76| 2022.00|  2023.00|  2023.00|   2024.00|   2024.00|▃▁▆▁▇ |\n|driver_age                  |         0|             1|    49.01|    12.07|   18.00|    39.00|    48.00|     58.00|     90.00|▂▇▇▃▁ |\n|vehicle_age                 |         2|             1|    25.92|    11.62|    0.00|    17.00|    25.00|     35.00|     68.00|▃▇▆▂▁ |\n|age_driving_licence         |         2|             1|    22.99|     6.36|    0.00|    19.00|    20.00|     25.00|     80.00|▁▇▁▁▁ |\n|vehicle_value               |       513|             1| 26977.44| 12326.09| 1630.12| 18607.58| 24729.60|  32252.32| 374034.21|▇▁▁▁▁ |\n|seats                       |         0|             1|     5.08|     0.76|    2.00|     5.00|     5.00|      5.00|      9.00|▁▁▇▁▁ |\n|power_to_weight_ratio       |         0|             1|    12.33|     2.48|    0.00|    10.74|    12.05|     13.73|     64.81|▇▅▁▁▁ |\n|total_premium               |         0|             1|   296.72|   227.85|    0.00|   146.14|   257.90|    384.98|   5107.64|▇▁▁▁▁ |\n|liability_premium           |         0|             1|   180.71|   129.72|    0.00|    92.52|   165.78|    237.83|   2320.77|▇▁▁▁▁ |\n|property_damage_premium     |         0|             1|    73.52|   155.80|    0.00|     0.00|     0.00|     83.62|   3736.73|▇▁▁▁▁ |\n|theft_premium               |         0|             1|    11.25|    18.99|    0.00|     1.81|     5.90|     13.52|   1047.04|▇▁▁▁▁ |\n|fire_premium                |         0|             1|     1.51|     2.25|    0.00|     0.29|     0.86|      1.82|     72.09|▇▁▁▁▁ |\n|glass_premium               |         0|             1|    19.50|    16.93|    0.00|     7.42|    15.39|     26.91|    387.61|▇▁▁▁▁ |\n|legal_protection_premium    |         0|             1|     8.27|     6.04|    0.00|     3.82|     7.26|     10.97|    175.06|▇▁▁▁▁ |\n|occupants_premium           |         0|             1|     1.97|     1.32|    0.00|     0.94|     1.83|      2.62|     68.65|▇▁▁▁▁ |\n|total_claims                |         0|             1|     0.22|     0.66|    0.00|     0.00|     0.00|      0.00|     18.00|▇▁▁▁▁ |\n|liability_claims            |         0|             1|     0.11|     0.38|    0.00|     0.00|     0.00|      0.00|      8.00|▇▁▁▁▁ |\n|liability_property_claims   |         0|             1|     0.09|     0.32|    0.00|     0.00|     0.00|      0.00|      8.00|▇▁▁▁▁ |\n|liability_injury_claims     |         0|             1|     0.01|     0.12|    0.00|     0.00|     0.00|      0.00|      3.00|▇▁▁▁▁ |\n|property_claims             |         0|             1|     0.06|     0.42|    0.00|     0.00|     0.00|      0.00|     15.00|▇▁▁▁▁ |\n|theft_claims                |         0|             1|     0.01|     0.07|    0.00|     0.00|     0.00|      0.00|      2.00|▇▁▁▁▁ |\n|fire_claims                 |         0|             1|     0.00|     0.02|    0.00|     0.00|     0.00|      0.00|      1.00|▇▁▁▁▁ |\n|glass_claims                |         0|             1|     0.03|     0.18|    0.00|     0.00|     0.00|      0.00|      3.00|▇▁▁▁▁ |\n|legal_protection_claims     |         0|             1|     0.01|     0.10|    0.00|     0.00|     0.00|      0.00|      2.00|▇▁▁▁▁ |\n|occupants_claims            |         0|             1|     0.00|     0.01|    0.00|     0.00|     0.00|      0.00|      1.00|▇▁▁▁▁ |\n|total_incurred              |         0|             1|   208.58|  2274.71|    0.00|     0.00|     0.00|      0.00| 571128.32|▇▁▁▁▁ |\n|liability_incurred          |         0|             1|   133.71|  2120.43|    0.00|     0.00|     0.00|      0.00| 561759.79|▇▁▁▁▁ |\n|liability_property_incurred |         0|             1|    65.74|   406.86|    0.00|     0.00|     0.00|      0.00|  34553.88|▇▁▁▁▁ |\n|liability_injury_incurred   |         0|             1|    67.96|  2031.21|    0.00|     0.00|     0.00|      0.00| 560025.59|▇▁▁▁▁ |\n|property_incurred           |         0|             1|    52.66|   420.99|    0.00|     0.00|     0.00|      0.00|  27542.43|▇▁▁▁▁ |\n|theft_incurred              |         0|             1|     4.51|   193.74|    0.00|     0.00|     0.00|      0.00|  40324.89|▇▁▁▁▁ |\n|fire_incurred               |         0|             1|     0.76|    82.03|    0.00|     0.00|     0.00|      0.00|  28267.13|▇▁▁▁▁ |\n|glass_incurred              |         0|             1|    12.59|    83.80|    0.00|     0.00|     0.00|      0.00|   4533.40|▇▁▁▁▁ |\n|legal_protection_incurred   |         0|             1|     3.32|    59.97|    0.00|     0.00|     0.00|      0.00|   9889.85|▇▁▁▁▁ |\n|occupants_incurred          |         0|             1|     1.01|   201.06|    0.00|     0.00|     0.00|      0.00|  69000.00|▇▁▁▁▁ |\n|total_exposure              |         0|             1|     0.71|     0.33|    0.00|     0.44|     0.84|      1.00|      1.00|▂▂▂▂▇ |\n|liability_exposure          |         0|             1|     0.71|     0.33|    0.00|     0.44|     0.84|      1.00|      1.00|▂▂▂▂▇ |\n\n\n:::\n:::\n\n\n### Data Pre-Processing\n\nAfter doing data exploration, we can quickly see some issues with our dataset.\n\n**Missing Value Treatment:**\n\n- `fuel_type`: 1,287 missing values (0.2%) removed due to negligible impact.\n- `age_driving_licence`: 2 missing values (\\<0.001%) removed due to negligible impact\n- `vehicle_age`: 2 missing values (\\<0.001%) removed due to negligible impact\n- `vehicle_value`: 513 missing values (0.08%) removed due to negligible impact\n\n**Features Engineering:**\n\n- `profitability`: total_premium - total_incurred\n- `profit_ratio`: profitability / total_premium\n- `has_claim`: \"Yes\" if total_incurred \\> 0, \"No\" otherwise\n- `years_with_licence`: year - age_driving_licence (actual years of driving experience)\n\n**Data Cleaning:**\n\n- We will filter rows with null profitability. This is due to null total_premium and/or total_incurred.\n- We will filter rows with null age_driving_licence.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean <- insurance_data %>%\n  mutate(\n    years_with_licence = year - age_driving_licence,\n    profitability = total_premium - total_incurred,\n    profit_ratio = ifelse(total_premium > 0, profitability / total_premium, NA),\n    has_claim = ifelse(total_incurred > 0, \"Yes\", \"No\")\n  ) %>%\n  filter(!is.na(profitability), !is.na(age_driving_licence), !is.na(vehicle_age), !is.na(fuel_type), !is.na(vehicle_value))\n\ncat(\"Original records:\", nrow(insurance_data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOriginal records: 354140 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"After cleaning:\", nrow(insurance_clean), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAfter cleaning: 352338 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Records removed:\", nrow(insurance_data) - nrow(insurance_clean), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRecords removed: 1802 \n```\n\n\n:::\n:::\n\n\n### Distribution Assessment and Statistical Test Selection\n\nBefore conducting statistical tests, we assess the normality of key numerical variables to determine whether parametric or non-parametric tests are appropriate.\n\n#### Q-Q Plots for Normality Assessment\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_qq1 <- ggplot(insurance_clean, aes(sample = total_premium)) +\n  stat_qq(alpha = 0.4) +\n  stat_qq_line(color = \"red\") +\n  labs(\n    title = \"Q-Q Plot: Premium\",\n    x = \"Theoretical Quantiles\",\n    y = \"Sample Quantiles\"\n  ) +\n  theme_minimal()\n\np_qq2 <- ggplot(insurance_clean, aes(sample = total_incurred)) +\n  stat_qq(alpha = 0.4) +\n  stat_qq_line(color = \"red\") +\n  labs(\n    title = \"Q-Q Plot: Claims\",\n    x = \"Theoretical Quantiles\",\n    y = \"Sample Quantiles\"\n  ) +\n  theme_minimal()\n\np_qq3 <- ggplot(insurance_clean, aes(sample = profitability)) +\n  stat_qq(alpha = 0.4) +\n  stat_qq_line(color = \"red\") +\n  labs(\n    title = \"Q-Q Plot: Profitability\",\n    x = \"Theoretical Quantiles\",\n    y = \"Sample Quantiles\"\n  ) +\n  theme_minimal()\n\n(p_qq1 | p_qq2) / p_qq3\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-6-1.png){width=1152}\n:::\n:::\n\n\n**Interpretation:** The Q-Q plots show clear deviations from the theoretical normal line for all three variables. total_premium displays right-skewness, while total_incurred has a very heavy right tail due to large claim observations. profitability shows strong left-tail deviation, suggesting the presence of extreme negative profitability cases. Therefore, the normality assumption is not satisfied, and non-parametric tests such as the Mann-Whitney U test and Kruskal-Wallis test are more appropriate for subsequent group comparisons.\n\n### Visual Analytics Approach\n\nThis analysis employs a systematic visual analytics strategy to explore the insurance portfolio data:\n\n**Univariate Analysis:**\n\n- **Histograms with density curves** to reveal distribution shapes, identify skewness, and detect multimodality\n- **Boxplots** to identify outliers, visualize quartile ranges, and assess data spread\n- **Log transformations** to demonstrate data transformation techniques for handling skewed distributions and to show how transformations affect interpretability\n\n**Bivariate Analysis:**\n\n- **Scatter plots with correlation coefficients** to assess the strength and direction of relationships (linear relationship) between continuous variables\n- **Grouped bar charts** to compare mean values across categorical groups\n- **Ridgeline plots** (from ggridges package) to compare full distributions across multiple groups simultaneously, showing both central tendency and spread\n- **Raincloud plots** (from ggdist package) to combine density curves, boxplots, and individual data points in a single visualization, providing comprehensive distributional information\n- **Error bar plots with confidence intervals** to quantify uncertainty in estimates and enable visual assessment of statistical significance\n\n**Statistical Validation:**\n\n- **ggbetweenstats** (from ggstatsplot package) to combine visualization with statistical testing, providing p-values, effect sizes, and pairwise comparisons in a single plot\n- **Non-parametric tests** (Kruskal-Wallis, Mann-Whitney) chosen based on Q-Q plot assessment showing non-normal distributions\n\nThis multi-layered approach ensures that findings are both visually interpretable and statistically validated, supporting evidence-based recommendations for portfolio management.\n\n## Analysis\n\n## Part 1: Univariate Visual Analytics\n\n### Numerical Variables\n\n#### Distribution of Premium\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(insurance_clean, aes(x = total_premium)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 50, fill = \"steelblue\", alpha = 0.7) +\n  geom_density(color = \"red\", linewidth = 1) +\n  scale_x_continuous(labels = comma) +\n  labs(\n    title = \"Distribution of Premium\",\n    x = \"Premium (€)\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n\np2 <- ggplot(insurance_clean, aes(y = total_premium)) +\n  geom_boxplot(fill = \"steelblue\", alpha = 0.7) +\n  scale_y_continuous(labels = comma) +\n  coord_flip() +\n  labs(\n    title = \"Boxplot of Premium\",\n    x = NULL,\n    y = \"Premium (€)\"\n  ) +\n  theme_minimal()\n\np1 / p2\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The distribution of total premium is right-skewed, with most policies having relatively low premium values. The histogram shows that the majority of observations are concentrated below €500, while a small number of policies have much higher premiums, extending beyond €5,000. The boxplot confirms the presence of several upper-tail outliers. Therefore, the premium variable is not normally distributed. A log transformation is applied below for visualization purposes only to better display the distribution shape.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(insurance_clean, aes(x = log1p(total_premium))) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 50, fill = \"steelblue\", alpha = 0.7) +\n  geom_density(color = \"red\", linewidth = 1) +\n  labs(\n    title = \"Distribution of Premium after Log Transformation\",\n    x = \"log(1 + Premium)\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n#### Distribution of Claims\n\n\n::: {.cell}\n\n```{.r .cell-code}\np3 <- ggplot(insurance_clean, aes(x = total_incurred)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 50, fill = \"coral\", alpha = 0.7) +\n  geom_density(color = \"darkred\", linewidth = 1) +\n  scale_x_continuous(labels = comma) +\n  labs(title = \"Distribution of Claim Costs\", x = \"Claim Cost (€)\", y = \"Density\") +\n  theme_minimal()\n\np4 <- ggplot(insurance_clean, aes(x = total_incurred)) +\n  geom_boxplot(fill = \"coral\", alpha = 0.7) +\n  scale_x_continuous(labels = comma) +\n  labs(title = \"Boxplot of Claim Costs\", x = \"Claim Cost (€)\") +\n  theme_minimal()\n\np3 / p4\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The distribution of total incurred claim costs is extremely right-skewed. Most policies have very low or zero claim costs, while a small number of observations have exceptionally large claim amounts, reaching nearly €600,000. The boxplot confirms the presence of many upper-tail outliers. This pattern is common in insurance data, where most policyholders do not make large claims, but a few severe claims can significantly affect the overall distribution. Therefore, the variable is not normally distributed, and log transformation or non-parametric methods may be more appropriate for further analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean <- insurance_clean %>%\n  mutate(log_total_incurred = log1p(total_incurred))\n\np3_log <- ggplot(insurance_clean, aes(x = log_total_incurred)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 50, fill = \"coral\", alpha = 0.7) +\n  geom_density(color = \"darkred\", linewidth = 1) +\n  labs(\n    title = \"Distribution of Claim Costs after Log Transformation\",\n    x = \"log(1 + Claim Cost)\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n\np4_log <- ggplot(insurance_clean, aes(y = log_total_incurred)) +\n  geom_boxplot(fill = \"coral\", alpha = 0.7) +\n  coord_flip() +\n  labs(\n    title = \"Boxplot of Claim Costs after Log Transformation\",\n    x = NULL,\n    y = \"log(1 + Claim Cost)\"\n  ) +\n  theme_minimal()\n\np3_log / p4_log\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** After applying the log transformation, the distribution of claim costs becomes easier to inspect, but a large spike remains at zero. This indicates that many policies have no incurred claims. Among policies with positive claim costs, the distribution is still right-skewed, although the log transformation reduces the influence of extreme claim values.\n\nLet's take a look at the distribution of positive claims only.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclaims_positive <- insurance_clean %>%\n  filter(total_incurred > 0) %>%\n  mutate(log_total_incurred = log(total_incurred))\n\np3_log_positive <- ggplot(claims_positive, aes(x = log_total_incurred)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 50, fill = \"coral\", alpha = 0.7) +\n  geom_density(color = \"darkred\", linewidth = 1) +\n  labs(\n    title = \"Distribution of Positive Claim Costs after Log Transformation\",\n    subtitle = \"Only policies with total incurred claims greater than zero are included\",\n    x = \"log(Claim Cost)\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n\np4_log_positive <- ggplot(claims_positive, aes(y = log_total_incurred)) +\n  geom_boxplot(fill = \"coral\", alpha = 0.7) +\n  coord_flip() +\n  labs(\n    title = \"Boxplot of Positive Claim Costs after Log Transformation\",\n    x = NULL,\n    y = \"log(Claim Cost)\"\n  ) +\n  theme_minimal()\n\np3_log_positive / p4_log_positive\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The log-transformed distribution of positive claims shows that claim amounts span a wide range, from small claims (low log values) to large claims (high log values). Low log values simply represent legitimately small claim payments (e.g., log(100) ≈ 4.6). The distribution remains right-skewed even after log transformation, so non-parametric or robust methods remain appropriate for comparing claim costs across groups.\n\n#### Distribution of Profitability\n\n\n::: {.cell}\n\n```{.r .cell-code}\np5 <- ggplot(insurance_clean, aes(x = profitability)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 50, fill = \"forestgreen\", alpha = 0.7) +\n  geom_density(color = \"darkgreen\", linewidth = 1) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"red\") +\n  scale_x_continuous(labels = comma) +\n  labs(\n    title = \"Distribution of Profitability\",\n    subtitle = \"Profitability = Premium - Claims\",\n    x = \"Profitability (€)\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n\np6 <- ggplot(insurance_clean, aes(y = profitability)) +\n  geom_boxplot(fill = \"forestgreen\", alpha = 0.7) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  scale_y_continuous(labels = comma) +\n  coord_flip() +\n  labs(\n    title = \"Boxplot of Profitability\",\n    x = NULL,\n    y = \"Profitability (€)\"\n  ) +\n  theme_minimal()\n\np5 / p6\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Profitability, defined as total premium minus total incurred claims, shows a highly left-skewed distribution. Most policies have profitability close to zero or moderately positive, while a small number of policies generate very large losses due to high claim costs. The vertical dashed line at zero separates profitable and loss-making policies. The long negative tail indicates that claim severity has a strong impact on insurer profitability. Therefore, profitability is not normally distributed, and non-parametric methods or transformed visualizations are more appropriate for further analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean <- insurance_clean %>%\n  mutate(signed_log_profitability = sign(profitability) * log1p(abs(profitability)))\n\nggplot(insurance_clean, aes(x = signed_log_profitability)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 50, fill = \"forestgreen\", alpha = 0.7) +\n  geom_density(color = \"darkgreen\", linewidth = 1) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"red\") +\n  labs(\n    title = \"Distribution of Profitability after Signed Log Transformation\",\n    x = \"sign(profitability) × log(1 + |profitability|)\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The transformed distribution shows two distinct regions: a large cluster of profitable policies and a smaller group of loss-making policies. Most observations are concentrated on the positive side of zero, while the negative tail indicates policies where incurred claims exceed premiums. This confirms that profitability is not normally distributed and supports the use of non-parametric methods in subsequent analyses.\n\n#### Distribution of Vehicle Age\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_vage1 <- ggplot(insurance_clean, aes(x = vehicle_age)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 30, fill = \"steelblue\", alpha = 0.7) +\n  geom_density(color = \"red\", linewidth = 1) +\n  labs(title = \"Distribution of Vehicle Age\", x = \"Vehicle Age (years)\", y = \"Density\") +\n  theme_minimal()\n\np_vage2 <- ggplot(insurance_clean, aes(y = vehicle_age)) +\n  geom_boxplot(fill = \"steelblue\", alpha = 0.7) +\n  coord_flip() +\n  labs(title = \"Boxplot of Vehicle Age\", x = NULL, y = \"Vehicle Age (years)\") +\n  theme_minimal()\n\np_vage1 / p_vage2\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The distribution of vehicle_age is not uniform. Most vehicles are concentrated between approximately 10 and 45 years old, with the highest density around 15–30 years. There are relatively fewer very new vehicles and fewer vehicles older than 50 years. Based on this distribution, vehicle_age was grouped into wider age bands: 0-5, 6-10, 11-20, 21-30, 31-40, 41-50, and 50+ years. This binning approach improves interpretability while preserving the main structure of the original distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean <- insurance_clean %>%\n  mutate(\n    vehicle_age_group = case_when(\n      vehicle_age < 0 ~ \"Invalid\",\n      vehicle_age <= 5 ~ \"0-5 years\",\n      vehicle_age <= 10 ~ \"6-10 years\",\n      vehicle_age <= 20 ~ \"11-20 years\",\n      vehicle_age <= 30 ~ \"21-30 years\",\n      vehicle_age <= 40 ~ \"31-40 years\",\n      vehicle_age <= 50 ~ \"41-50 years\",\n      TRUE ~ \"50+ years\"\n    ),\n    vehicle_age_group = factor(\n      vehicle_age_group,\n      levels = c(\n        \"Invalid\", \"0-5 years\", \"6-10 years\", \"11-20 years\",\n        \"21-30 years\", \"31-40 years\", \"41-50 years\", \"50+ years\"\n      )\n    )\n  )\n```\n:::\n\n\n#### Distribution of Driver Age\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_dage1 <- ggplot(insurance_clean, aes(x = driver_age)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 30, fill = \"coral\", alpha = 0.7) +\n  geom_density(color = \"darkred\", linewidth = 1) +\n  labs(title = \"Distribution of Driver Age\", x = \"Driver Age (years)\", y = \"Density\") +\n  theme_minimal()\n\np_dage2 <- ggplot(insurance_clean, aes(y = driver_age)) +\n  geom_boxplot(fill = \"coral\", alpha = 0.7) +\n  coord_flip() +\n  labs(title = \"Boxplot of Driver Age\", x = NULL, y = \"Driver Age (years)\") +\n  theme_minimal()\n\np_dage1 / p_dage2\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** From the distribution, most drivers are between around 35 and 65 years old, with the highest density around the late 30s to early 50s. The distribution is slightly right-skewed, with a small number of older drivers above 80 appearing as outliers in the boxplot. Since age may have a non-linear relationship with profitability and claim risk, grouping driver age into age bands makes the analysis easier to interpret.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean <- insurance_clean %>%\n  mutate(\n    driver_age_group = case_when(\n      driver_age <= 25 ~ \"18-25 years\",\n      driver_age <= 35 ~ \"26-35 years\",\n      driver_age <= 50 ~ \"36-50 years\",\n      driver_age <= 65 ~ \"51-65 years\",\n      TRUE ~ \"65+ years\"\n    ),\n    driver_age_group = factor(\n      driver_age_group,\n      levels = c(\"18-25 years\", \"26-35 years\", \"36-50 years\", \"51-65 years\", \"65+ years\")\n    )\n  )\n```\n:::\n\n\nThis grouping improves interpretability and allows profitability patterns to be compared across different driver age segments.\n\n#### Distribution of Driving License Age\n\nThe variable years_with_licence was derived earlier as year - age_driving_licence, representing the actual years of driving experience. This variable is more interpretable for analysing claim risk and profitability than the raw licence year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_lage1 <- ggplot(insurance_clean, aes(x = years_with_licence)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 30, fill = \"forestgreen\", alpha = 0.7) +\n  geom_density(color = \"darkgreen\", linewidth = 1) +\n  labs(\n    title = \"Distribution of Driving Experience\",\n    x = \"Years Since Licence Obtained\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n\np_lage2 <- ggplot(insurance_clean, aes(y = years_with_licence)) +\n  geom_boxplot(fill = \"forestgreen\", alpha = 0.7) +\n  coord_flip() +\n  labs(\n    title = \"Boxplot of Driving Experience\",\n    x = NULL,\n    y = \"Years Since Licence Obtained\"\n  ) +\n  theme_minimal()\n\np_lage1 / p_lage2\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The distribution of driving experience is highly right-skewed. Most drivers have around 18 to 25 years since obtaining their licence, with the highest concentration close to 20 years. The boxplot also shows several outliers, especially among drivers with more than 40 years of experience, and a few very low values close to zero. This suggests that the variable is not evenly distributed and may have a non-linear relationship with profitability or claim risk. Therefore, driving experience was converted into grouped categories to make the analysis easier to interpret and reduce the influence of individual extreme values.\n\nBased on this distribution, driving experience was grouped into 0-10, 11-20, 21-30, 31-40, and 40+ years. Wider groups were used because most observations are concentrated around 18–25 years, while the higher-experience values form a long tail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean <- insurance_clean %>%\n  mutate(\n    driving_experience_group = case_when(\n      years_with_licence < 0 ~ \"Invalid\",\n      years_with_licence <= 10 ~ \"0-10 years\",\n      years_with_licence <= 20 ~ \"11-20 years\",\n      years_with_licence <= 30 ~ \"21-30 years\",\n      years_with_licence <= 40 ~ \"31-40 years\",\n      TRUE ~ \"40+ years\"\n    ),\n    driving_experience_group = factor(\n      driving_experience_group,\n      levels = c(\n        \"Invalid\", \"0-10 years\", \"11-20 years\",\n        \"21-30 years\", \"31-40 years\", \"40+ years\"\n      )\n    )\n  )\n```\n:::\n\n\n#### Distribution of Weight-to-Power Ratio\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_pwr1 <- ggplot(insurance_clean, aes(x = power_to_weight_ratio)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 30, fill = \"purple\", alpha = 0.7) +\n  geom_density(color = \"darkviolet\", linewidth = 1) +\n  labs(\n    title = \"Distribution of Weight-to-Power Ratio\",\n    x = \"Weight-to-Power Ratio (kg per horsepower)\",\n    y = \"Density\"\n  ) +\n  theme_minimal()\n\np_pwr2 <- ggplot(insurance_clean, aes(y = power_to_weight_ratio)) +\n  geom_boxplot(fill = \"purple\", alpha = 0.7) +\n  coord_flip() +\n  labs(\n    title = \"Boxplot of Weight-to-Power Ratio\",\n    x = NULL,\n    y = \"Weight-to-Power Ratio (kg per horsepower)\"\n  ) +\n  theme_minimal()\n\np_pwr1 / p_pwr2\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The distribution of weight-to-power ratio is strongly right-skewed. Most vehicles are concentrated around approximately 8 to 15 kg per horsepower, while a smaller number of vehicles have much higher ratios. The boxplot also shows several high-end outliers, including one extreme value above 60. Since this variable is measured as kg per horsepower, a lower value indicates stronger vehicle performance, while a higher value indicates lower performance relative to vehicle weight. Therefore, the variable was grouped into categories to improve interpretability and reduce the influence of individual extreme values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean <- insurance_clean %>%\n  mutate(\n    weight_power_group = cut(\n      power_to_weight_ratio,\n      breaks = quantile(\n        power_to_weight_ratio,\n        probs = c(0, 0.25, 0.5, 0.75, 1),\n        na.rm = TRUE\n      ),\n      include.lowest = TRUE,\n      labels = c(\"Low ratio / High performance\",\n                 \"Medium-low ratio\",\n                 \"Medium-high ratio\",\n                 \"High ratio / Low performance\")\n    )\n  )\n```\n:::\n\n\n#### Distribution of Total Exposure\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_exp1 <- ggplot(insurance_clean, aes(x = total_exposure)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 30, fill = \"orange\", alpha = 0.7) +\n  geom_density(color = \"darkorange\", linewidth = 1) +\n  labs(title = \"Distribution of Total Exposure\", x = \"Total Exposure (years)\", y = \"Density\") +\n  theme_minimal()\n\np_exp2 <- ggplot(insurance_clean, aes(y = total_exposure)) +\n  geom_boxplot(fill = \"orange\", alpha = 0.7) +\n  coord_flip() +\n  labs(title = \"Boxplot of Total Exposure\", x = NULL, y = \"Total Exposure (years)\") +\n  theme_minimal()\n\np_exp1 / p_exp2\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The distribution of total_exposure shows that many policies have exposure close to 1 year, meaning they were active for almost the full policy period. However, there are also many partial-year policies with exposure values below 1. The boxplot shows that the median exposure is relatively high, around 0.8–0.9 years, while the lower quartile is around 0.4–0.5 years. Since exposure measures the amount of time a policy is active, it affects both premium earned and claim opportunity. Therefore, total_exposure should be considered when interpreting profitability and claim risk.\n\nBecause exposure is bounded between 0 and 1 and has a large concentration near 1, it was grouped into exposure bands to compare short-term and full-year policies more clearly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean <- insurance_clean %>%\n  mutate(\n    exposure_group = case_when(\n      is.na(total_exposure) ~ NA_character_,\n      total_exposure < 0.25 ~ \"Very short exposure\",\n      total_exposure < 0.50 ~ \"Short exposure\",\n      total_exposure < 0.75 ~ \"Medium exposure\",\n      total_exposure < 1.00 ~ \"High exposure\",\n      total_exposure >= 1.00 ~ \"Full-year exposure\",\n      TRUE ~ \"Other\"\n    ),\n    exposure_group = factor(\n      exposure_group,\n      levels = c(\n        \"Very short exposure\",\n        \"Short exposure\",\n        \"Medium exposure\",\n        \"High exposure\",\n        \"Full-year exposure\"\n      )\n    )\n  )\n```\n:::\n\n\n### Categorical Variables\n\n#### Fuel Type Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean %>%\n  count(fuel_type) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(fuel_type, n), y = n, fill = fuel_type)) +\n  geom_col() +\n  geom_text(\n    aes(label = paste0(round(pct, 1), \"%\")),\n    hjust = -0.1\n  ) +\n  coord_flip() +\n  scale_y_continuous(\n    labels = comma,\n    expand = expansion(mult = c(0, 0.15))\n  ) +\n  labs(\n    title = \"Distribution of Fuel Types\",\n    x = \"Fuel Type\",\n    y = \"Count\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The fuel type distribution is highly imbalanced. Diesel vehicles account for the majority of the portfolio, representing around 64.2% of policies, followed by gasoline vehicles at 35.8%.\n\n#### Geographic Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean %>%\n  count(circulation_area) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(circulation_area, n), y = n, fill = circulation_area)) +\n  geom_col() +\n  geom_text(\n    aes(label = paste0(round(pct, 1), \"%\")),\n    hjust = -0.1\n  ) +\n  coord_flip() +\n  scale_y_continuous(\n    labels = comma,\n    expand = expansion(mult = c(0, 0.15))\n  ) +\n  labs(\n    title = \"Distribution by Circulation Area\",\n    x = \"Area\",\n    y = \"Count\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Area U is slightly more common, but both R and U have substantial sample sizes.\n\n#### Municipality Type Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean %>%\n  count(municipality_type) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(municipality_type, n), y = n, fill = municipality_type)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")), hjust = -0.1) +\n  coord_flip() +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.15))) +\n  labs(title = \"Distribution by Municipality Type\", x = \"Municipality Type\", y = \"Count\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The distribution of municipality_type shows that most policyholders are from inland municipalities, accounting for 64.6% of the dataset. Coastal municipalities represent 28.6%, while island municipalities account for only 6.8%. This indicates that the portfolio is geographically imbalanced, with inland areas dominating the sample. Since municipality type may reflect different driving environments, road conditions, traffic density, and claim exposure, it is useful to include this variable when comparing claim risk and profitability. However, results for the island group should be interpreted carefully because it has a much smaller sample size.\n\nRecode the labels for readability only.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean <- insurance_clean %>%\n  mutate(\n    municipality_type_label = case_when(\n      municipality_type == \"I\" ~ \"Inland\",\n      municipality_type == \"C\" ~ \"Coastal\",\n      municipality_type == \"IS\" ~ \"Islands\",\n      TRUE ~ \"Other\"\n    ),\n    municipality_type_label = factor(\n      municipality_type_label,\n      levels = c(\"Inland\", \"Coastal\", \"Islands\", \"Other\")\n    )\n  )\n\ninsurance_clean %>%\n  count(municipality_type_label) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(municipality_type_label, n), y = n, fill = municipality_type_label)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")), hjust = -0.1) +\n  coord_flip() +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.15))) +\n  labs(\n    title = \"Distribution by Municipality Type\",\n    x = \"Municipality Type\",\n    y = \"Count\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n#### Bonus Score Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean %>%\n  count(bonus_score) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(bonus_score, n), y = n, fill = bonus_score)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")), hjust = -0.1) +\n  coord_flip() +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.15))) +\n  labs(title = \"Distribution by Bonus Score\", x = \"Bonus Score\", y = \"Count\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The distribution of bonus_score is highly imbalanced. The majority of policyholders are classified as G, representing a favourable claims history, and this group accounts for 96.4% of the dataset. The N group, representing a neutral profile, accounts for only 2.2%, while the B group, representing a poor claims history, accounts for 1.3%. This suggests that most policyholders in the portfolio have a positive claims history. However, because the N and B groups are very small, any profitability or claim-risk comparison involving these groups should be interpreted carefully.\n\nRecode the labels for readability.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean <- insurance_clean %>%\n  mutate(\n    bonus_score_label = case_when(\n      bonus_score == \"G\" ~ \"Good claims history\",\n      bonus_score == \"N\" ~ \"Neutral profile\",\n      bonus_score == \"B\" ~ \"Poor claims history\",\n      TRUE ~ \"Other\"\n    ),\n    bonus_score_label = factor(\n      bonus_score_label,\n      levels = c(\"Good claims history\", \"Neutral profile\", \"Poor claims history\", \"Other\")\n    )\n  )\n\ninsurance_clean %>%\n  count(bonus_score_label) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(bonus_score_label, n), y = n, fill = bonus_score_label)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")), hjust = -0.1) +\n  coord_flip() +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.15))) +\n  labs(title = \"Distribution by Bonus Score\", x = \"Bonus Score\", y = \"Count\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n#### Policy Type Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean %>%\n  count(policy_type) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(policy_type, n), y = n, fill = policy_type)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")), hjust = -0.1) +\n  coord_flip() +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.15))) +\n  labs(title = \"Distribution by Policy Type\", x = \"Policy Type\", y = \"Count\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The distribution of policy_type shows that the portfolio is mainly concentrated in CC policies, which account for 57.9% of all observations. The second largest group is COMP_E, representing 25.6%, followed by TPG at 10.3%. In contrast, COMP_N and TP are much smaller groups, accounting for only 4.5% and 1.6%, respectively. This indicates that most policies include third-party liability combined with additional coverages, while basic third-party-only policies are relatively rare.\n\nSince policy type represents the coverage structure of the insurance contract, it is expected to be closely related to premium, claim cost, and profitability. Policies with broader coverage may generate higher premiums but may also expose the insurer to more types of claims. Therefore, policy_type is an important variable for comparing profitability and claim risk across different insurance products.\n\nHowever, the smaller sample sizes for TP and COMP_N mean that results for these groups should be interpreted carefully, as their profitability patterns may be less stable.\n\nRecode the labels for readability.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean <- insurance_clean %>%\n  mutate(\n    policy_type_label = case_when(\n      policy_type == \"TP\" ~ \"Third-party only\",\n      policy_type == \"TPG\" ~ \"Third-party + glass\",\n      policy_type == \"CC\" ~ \"Third-party + add-ons\",\n      policy_type == \"COMP_E\" ~ \"Comprehensive with excess\",\n      policy_type == \"COMP_N\" ~ \"Comprehensive without excess\",\n      TRUE ~ \"Other\"\n    ),\n    policy_type_label = factor(\n      policy_type_label,\n      levels = c(\n        \"Third-party only\",\n        \"Third-party + glass\",\n        \"Third-party + add-ons\",\n        \"Comprehensive with excess\",\n        \"Comprehensive without excess\",\n        \"Other\"\n      )\n    )\n  )\n\ninsurance_clean %>%\n  count(policy_type_label) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = reorder(policy_type_label, n), y = n, fill = policy_type_label)) +\n  geom_col() +\n  geom_text(aes(label = paste0(round(pct, 1), \"%\")), hjust = -0.1) +\n  coord_flip() +\n  scale_y_continuous(labels = comma, expand = expansion(mult = c(0, 0.15))) +\n  labs(title = \"Distribution by Policy Type\", x = \"Policy Type\", y = \"Count\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n#### Claims Occurrence\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean %>%\n  count(has_claim) %>%\n  mutate(pct = n / sum(n) * 100) %>%\n  ggplot(aes(x = has_claim, y = n, fill = has_claim)) +\n  geom_col() +\n  geom_text(\n    aes(label = paste0(round(pct, 1), \"%\\n(n=\", scales::comma(n), \")\")),\n    vjust = -0.5\n  ) +\n  labs(\n    title = \"Policies with vs without Claims\",\n    x = \"Has Claim\",\n    y = \"Count\"\n  ) +\n  scale_y_continuous(\n    labels = comma,\n    expand = expansion(mult = c(0, 0.15))\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Most policies in the portfolio do not have any claims. Around 88.1% of policies have no claims, while only 11.9% have at least one claim. This indicates that claim occurrence is relatively rare, which is typical in motor insurance data. The strong imbalance also explains why the `total_incurred` variable has many zero values and a highly right-skewed distribution. For later modelling or statistical analysis, this imbalance should be considered carefully, especially if `has_claim` is used as a target variable.\n\nThis supports treating claim analysis as two parts: claim frequency and claim severity. claims are rare, data is imbalanced, and claim cost is zero-inflated because most policies have no claims.\n\n## Data Wrangling Summary\n\n### Data Exploration\n\nAfter importing the dataset, we performed initial exploration using `glimpse()` and `skim()` to understand the structure, data types, and quality of the variables. Key findings included:\n\n- Dataset contains 647,387 policy records with 46 variables\n- Missing values identified in `fuel_type` (1,287), `age_driving_licence` (2), `vehicle_age` (2), and `vehicle_value` (513)\n- Numerical variables show right-skewed distributions typical of insurance data\n- Categorical variables show imbalanced distributions\n\n### Data Processing\n\n**Missing Value Treatment:** - `fuel_type`: Removed 1,287 missing values (0.2%) due to negligible impact - `age_driving_licence` and `vehicle_age`: Removed 4 records with missing values due to negligible impact - `vehicle_value`: Kept as NA; filtered when analyzing vehicle value relationships\n\n**Feature Engineering:** - Created `profitability` = total_premium - total_incurred - Created `profit_ratio` = profitability / total_premium - Created `has_claim` indicator variable - Created `years_with_licence` = year - age_driving_licence (actual years of driving experience)\n\n**Binning and Grouping:** After exploring raw distributions, we created categorical groups for analysis: - `vehicle_age_group`: 8 categories from \"0-5 years\" to \"50+ years\" - `driver_age_group`: 5 categories from \"18-25 years\" to \"65+ years\" - `license_age_group`: 5 categories from \"0-5 years\" to \"30+ years\" (based on years_with_licence)\n\n### Variables Used in Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvariable_summary <- tibble(\n  Variable = c(\n    \"total_premium\", \"total_incurred\", \"profitability\",\n    \"vehicle_age\", \"driver_age\", \"years_with_licence\",\n    \"power_to_weight_ratio\", \"total_exposure\",\n    \"fuel_type\", \"circulation_area\", \"municipality_type\",\n    \"bonus_score\", \"policy_type\",\n    \"vehicle_age_group\", \"driver_age_group\", \"license_age_group\"\n  ),\n  Type = c(\n    \"Numeric\", \"Numeric\", \"Numeric (Derived)\",\n    \"Numeric\", \"Numeric\", \"Numeric (Derived)\",\n    \"Numeric\", \"Numeric\",\n    \"Categorical\", \"Categorical\", \"Categorical\",\n    \"Categorical\", \"Categorical\",\n    \"Categorical (Derived)\", \"Categorical (Derived)\", \"Categorical (Derived)\"\n  ),\n  Description = c(\n    \"Total premium of the policy, sum of all individual coverage premiums\",\n    \"Total incurred cost of claims including paid amounts and outstanding reserves\",\n    \"Derived: total_premium - total_incurred\",\n    \"Age of the insured vehicle in years\",\n    \"Age of the main driver in years\",\n    \"Derived: years of driving experience (policy year - licence year)\",\n    \"Weight-to-power ratio (kg per horsepower), proxy for vehicle performance\",\n    \"Effective time-on-risk in policy years (0-1 for partial year, >1 for multi-year)\",\n    \"Vehicle fuel type: D=diesel, G=gasoline, Unknown=missing\",\n    \"Predominant circulation environment: U=urban, R=rural\",\n    \"Geographic classification: I=inland, C=coastal, IS=islands\",\n    \"Policyholder's claims history: G=good/favorable, N=neutral, B=bad/poor\",\n    \"Coverage structure: TP, TPG, CC, COMP_E, COMP_N\",\n    \"Categorical groups based on vehicle age (8 categories)\",\n    \"Categorical groups based on driver age (5 categories)\",\n    \"Categorical groups based on years with licence (5 categories)\"\n  )\n)\n\nknitr::kable(variable_summary, caption = \"Variables Used in Analysis\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Variables Used in Analysis\n\n|Variable              |Type                  |Description                                                                      |\n|:---------------------|:---------------------|:--------------------------------------------------------------------------------|\n|total_premium         |Numeric               |Total premium of the policy, sum of all individual coverage premiums             |\n|total_incurred        |Numeric               |Total incurred cost of claims including paid amounts and outstanding reserves    |\n|profitability         |Numeric (Derived)     |Derived: total_premium - total_incurred                                          |\n|vehicle_age           |Numeric               |Age of the insured vehicle in years                                              |\n|driver_age            |Numeric               |Age of the main driver in years                                                  |\n|years_with_licence    |Numeric (Derived)     |Derived: years of driving experience (policy year - licence year)                |\n|power_to_weight_ratio |Numeric               |Weight-to-power ratio (kg per horsepower), proxy for vehicle performance         |\n|total_exposure        |Numeric               |Effective time-on-risk in policy years (0-1 for partial year, >1 for multi-year) |\n|fuel_type             |Categorical           |Vehicle fuel type: D=diesel, G=gasoline, Unknown=missing                         |\n|circulation_area      |Categorical           |Predominant circulation environment: U=urban, R=rural                            |\n|municipality_type     |Categorical           |Geographic classification: I=inland, C=coastal, IS=islands                       |\n|bonus_score           |Categorical           |Policyholder's claims history: G=good/favorable, N=neutral, B=bad/poor           |\n|policy_type           |Categorical           |Coverage structure: TP, TPG, CC, COMP_E, COMP_N                                  |\n|vehicle_age_group     |Categorical (Derived) |Categorical groups based on vehicle age (8 categories)                           |\n|driver_age_group      |Categorical (Derived) |Categorical groups based on driver age (5 categories)                            |\n|license_age_group     |Categorical (Derived) |Categorical groups based on years with licence (5 categories)                    |\n\n\n:::\n:::\n\n\n## Part 2: Bivariate Visual Analytics\n\n### Factors Influencing Profitability\n\n#### Premium vs Claims Relationship\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\n\ncor_value <- cor(\n  insurance_clean$total_premium,\n  insurance_clean$total_incurred,\n  method = \"spearman\",\n  use = \"complete.obs\"\n)\n\ninsurance_clean %>%\n  sample_n(min(5000, nrow(insurance_clean))) %>%\n  ggplot(aes(x = total_premium, y = total_incurred)) +\n  geom_point(alpha = 0.25, color = \"steelblue\") +\n  geom_smooth(method = \"loess\", color = \"red\", se = TRUE) +\n  scale_x_continuous(labels = comma) +\n  scale_y_continuous(labels = comma) +\n  labs(\n    title = \"Premium vs Claim Cost Relationship\",\n    subtitle = paste0(\"Spearman correlation: \", round(cor_value, 3)),\n    x = \"Premium (€)\",\n    y = \"Claim Cost (€)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Premium and claim cost have only a weak positive relationship. The Spearman correlation is 0.217, meaning higher-premium policies tend to have slightly higher claim costs, but the relationship is not strong.\n\nFiltering to positive claims only, the Spearman correlation remains weak at 0.14.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_positive <- cor(\n  claims_positive$total_premium,\n  claims_positive$total_incurred,\n  method = \"spearman\",\n  use = \"complete.obs\"\n)\n\nclaims_positive %>%\n  sample_n(min(5000, nrow(claims_positive))) %>%\n  ggplot(aes(x = total_premium, y = total_incurred)) +\n  geom_point(alpha = 0.25, color = \"steelblue\") +\n  geom_smooth(method = \"loess\", color = \"red\", se = TRUE) +\n  scale_x_continuous(labels = comma) +\n  scale_y_continuous(labels = comma) +\n  labs(\n    title = \"Premium vs Claim Cost Relationship among Claim Policies\",\n    subtitle = paste0(\"Positive claims only; Spearman correlation: \", round(cor_positive, 3)),\n    x = \"Premium (€)\",\n    y = \"Claim Cost (€)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n#### Profitability by Claim Occurrence\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_clean,\n  x = has_claim,\n  y = profitability,\n  type = \"nonparametric\",\n  pairwise.comparisons = TRUE,\n  p.adjust.method = \"bonferroni\",\n  title = \"Profitability Distribution by Claim Occurrence\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Claim occurrence shows the strongest relationship with profitability among all factors analyzed. The Mann-Whitney test reveals a highly significant difference (p \\< 0.001) with a large effect size. Policies without claims (No) have a median profitability of approximately €248, while policies with at least one claim (Yes) have dramatically lower median profitability, often negative or near zero. This confirms that claim occurrence is the most critical driver of profitability in the portfolio. However, this relationship is partially definitional: since profitability = premium − claims, policies without claims will mechanically have profitability equal to their full premium. The large effect size reflects this structural dependency rather than an independent risk insight.\n\nThe effect size is large, with r≈0.78, indicating that claim occurrence is one of the strongest factors associated with profitability. Unlike some previous variables where the statistical significance was mainly driven by the large sample size, the difference here is both statistically and practically meaningful.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean %>%\n  filter(profitability >= -2000, profitability <= 2000) %>%\n  ggplot(aes(x = has_claim, y = profitability, fill = has_claim)) +\n  geom_violin(alpha = 0.7, trim = TRUE) +\n  geom_boxplot(width = 0.2, alpha = 0.5, outlier.alpha = 0.2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  scale_y_continuous(labels = comma) +\n  labs(\n    title = \"Profitability by Claim Occurrence\",\n    subtitle = \"Filtered to profitability between -€2,000 and €2,000 for readability\",\n    x = \"Has Claim\",\n    y = \"Profitability (€)\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The violin plot clearly shows the dramatic difference in profitability distributions between policies with and without claims. Policies without claims are concentrated in positive profitability territory, with most values above zero. In contrast, policies with claims show a much wider distribution with substantial mass in negative profitability territory, indicating that claims directly erode profitability. This visual confirms that claim occurrence is the primary determinant of policy-level profitability.\n\n#### Profitability by Fuel Type\n\nSince profitability is highly non-normal and contains extreme outliers, a non-parametric approach was selected. The Kruskal-Wallis test was used instead of one-way ANOVA because it does not require the normality assumption and is more appropriate for comparing profitability distributions across fuel types.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_clean,\n  x = fuel_type,\n  y = profitability,\n  type = \"nonparametric\",\n  pairwise.comparisons = TRUE,\n  p.adjust.method = \"bonferroni\",\n  title = \"Profitability Distribution by Fuel Type\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The Mann-Whitney test shows a statistically significant difference in profitability between the two fuel types, with a very small p-value. Diesel (D) policies have a higher median profitability of approximately €240.75, compared with €216.22 for gasoline (G) policies. This suggests that diesel policies are typically slightly more profitable than gasoline policies.However, the effect size is negligible (r ≈ 0.08), meaning the practical difference between the two groups is limited despite being statistically significant. This is likely because the dataset is very large, so even small differences can become statistically significant.\n\n=\\> Fuel type is statistically associated with profitability, but the practical effect appears small.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean %>%\n  filter(profitability >= -2000, profitability <= 2000) %>%\n  ggplot(aes(x = fuel_type, y = profitability, fill = fuel_type)) +\n  geom_boxplot(alpha = 0.7, outlier.alpha = 0.25) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  labs(\n    title = \"Profitability by Fuel Type\",\n    subtitle = \"Filtered to profitability between -€2,000 and €2,000 for readability\",\n    x = \"Fuel Type\",\n    y = \"Profitability (€)\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n#### Ridgeline Plot: Profitability by Fuel Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean %>%\n  ggplot(aes(x = profitability, y = fuel_type, fill = fuel_type)) +\n  geom_density_ridges(scale = 0.9, alpha = 0.7) +\n  scale_x_continuous(labels = comma) +\n  coord_cartesian(xlim = c(-2000, 2000)) +\n  labs(\n    title = \"Profitability Distribution by Fuel Type\",\n    subtitle = \"Ridgeline plot showing distribution overlap and differences\",\n    x = \"Profitability (€)\",\n    y = \"Fuel Type\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The ridgeline plot compares the profitability distributions across different fuel types. Overall, the distributions largely overlap, suggesting that profitability patterns are broadly similar across fuel categories. Most policies are concentrated around slightly positive profitability values, while each fuel type also shows some negative-profitability cases. Diesel and gasoline vehicles appear to have similar central distributions.\n\nThe below plot is restricted to the central profitability range to improve readability because extreme loss values distort the density estimation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean %>%\n  filter(profitability >= -2000, profitability <= 2000) %>%\n  ggplot(aes(x = profitability, y = fuel_type, fill = fuel_type)) +\n  geom_density_ridges(scale = 0.9, alpha = 0.7, rel_min_height = 0.01) +\n  scale_x_continuous(labels = comma) +\n  labs(\n    title = \"Profitability Distribution by Fuel Type\",\n    subtitle = \"Zoomed view: profitability between -€2,000 and €2,000\",\n    x = \"Profitability (€)\",\n    y = \"Fuel Type\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n#### Profitability by Region\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_clean,\n  x = circulation_area,\n  y = profitability,\n  type = \"nonparametric\",\n  pairwise.comparisons = TRUE,\n  p.adjust.method = \"bonferroni\",\n  title = \"Profitability Distribution by Circulation Area\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Policies in area `U` show slightly higher median profitability than those in area `R`. The difference is statistically significant, but the effect size is very small, indicating that circulation area alone does not strongly explain profitability differences.\n\n=\\> Area matters statistically, but the practical difference is very small.\n\n#### Profitability by Vehicle Age\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(insurance_clean, aes(x = vehicle_age_group, y = profitability, fill = vehicle_age_group)) +\n  geom_violin(alpha = 0.7) +\n  geom_boxplot(width = 0.2, alpha = 0.5) +\n  scale_y_continuous(labels = comma) +\n  labs(title = \"Profitability by Vehicle Age Group\",\n       x = \"Vehicle Age (years)\", y = \"Profitability (€)\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Profitability varies across vehicle age groups, but the chart is strongly influenced by extreme negative outliers. Most policies in all age groups have profitability clustered close to zero, suggesting that typical profitability differences are not very large. However, older vehicle groups show more severe downside outcomes, with larger negative profitability outliers. This pattern is especially visible for vehicles aged 41–50 years and 50+ years, suggesting that very old vehicles may be associated with higher claim severity and greater loss risk. Therefore, older vehicles appear to carry greater downside risk, even if the majority of observations remain close to zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_clean %>%\n  filter(\n    profitability >= -2000,\n    profitability <= 2000,\n    !is.na(vehicle_age_group)\n  ) %>%\n  ggplot(aes(\n    x = vehicle_age_group,\n    y = profitability,\n    fill = vehicle_age_group\n  )) +\n  geom_violin(alpha = 0.7, trim = TRUE) +\n  geom_boxplot(width = 0.2, alpha = 0.5, outlier.alpha = 0.2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  scale_y_continuous(labels = comma) +\n  labs(\n    title = \"Profitability by Vehicle Age Group\",\n    subtitle = \"Filtered to profitability between -€2,000 and €2,000 for readability\",\n    x = \"Vehicle Age Group\",\n    y = \"Profitability (€)\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** After filtering extreme profitability values, most vehicle age groups have similar median profitability, generally slightly above zero. However, older vehicle groups, especially 41-50 years and 50+ years, show wider negative tails, suggesting greater downside risk. This indicates that while typical profitability is relatively stable across vehicle age groups, very old vehicles may be more exposed to severe loss outcomes.\n\n#### Profitability by Driver Age Group\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_clean,\n  x = driver_age_group,\n  y = profitability,\n  type = \"nonparametric\",\n  pairwise.comparisons = TRUE,\n  p.adjust.method = \"bonferroni\",\n  title = \"Profitability Distribution by Driver Age Group\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Profitability differs significantly across driver age groups based on the Kruskal-Wallis test, p\\<0.001. Younger drivers aged 18-25 show the highest median profitability, while the 36-50 and 65+ groups have lower median profitability. However, the effect size is very small, meaning the practical difference across age groups is limited. The result should also be interpreted carefully because the 18-25 group has a much smaller sample size than the other groups.\n\n#### Profitability by Driving Experience Group\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_clean,\n  x = driving_experience_group,\n  y = profitability,\n  type = \"nonparametric\",\n  pairwise.comparisons = TRUE,\n  p.adjust.method = \"bonferroni\",\n  title = \"Profitability Distribution by Driving Experience Group\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Interpretation: The Kruskal-Wallis test shows a statistically significant difference in profitability across driving experience groups, p\\<0.001. However, the effect size is extremely small, suggesting that driving experience explains only a very limited amount of the variation in profitability. Most groups have broadly similar median profitability, generally around €225–€237. The 0-10 years group has a much lower median profitability, but this group contains only 15 observations, so it should not be used for strong conclusions. Overall, driving experience appears to have a statistically detectable but practically weak relationship with profitability.\n\nSeveral groups also contain large negative profitability outliers, especially the 11-20 years, 21-30 years, and 31-40 years groups. This suggests that severe loss cases occur across different experience levels, not only among inexperienced drivers.\n\n#### Profitability by Municipality Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_clean,\n  x = municipality_type,\n  y = profitability,\n  type = \"nonparametric\",\n  pairwise.comparisons = TRUE,\n  p.adjust.method = \"bonferroni\",\n  title = \"Profitability Distribution by Municipality Type\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The Kruskal-Wallis test shows a statistically significant difference in profitability across municipality types, p\\<0.001. Coastal municipalities (C) have the highest median profitability at approximately €239.97, followed by inland municipalities (I) at €226.89, and island municipalities (IS) at €218.29. This suggests that profitability varies by geographic classification.\n\nHowever, the effect size is very small, meaning that municipality type explains only a limited amount of profitability variation. The statistical significance is likely partly driven by the very large sample size. In addition, the island group has a much smaller sample size than the coastal and inland groups, so its results should be interpreted more cautiously.\n\n#### Profitability by Bonus Score\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_clean,\n  x = bonus_score,\n  y = profitability,\n  type = \"nonparametric\",\n  pairwise.comparisons = TRUE,\n  p.adjust.method = \"bonferroni\",\n  title = \"Profitability Distribution by Bonus Score\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The Kruskal-Wallis test shows a statistically significant difference in profitability across bonus score groups, p\\<0.001. The B group has the highest median profitability at approximately €333.29, followed by N at €239.25 and G at €228.79. This result is somewhat unexpected because B represents a poorer claims history, so it may have been expected to show lower profitability.\n\nHowever, the effect size is very small, suggesting that bonus score explains only a limited amount of profitability variation. In addition, the dataset is highly imbalanced: the G group dominates the portfolio, while B and N have much smaller sample sizes. Therefore, although the statistical test is significant, the practical importance of the difference should be interpreted carefully.\n\n#### Profitability by Policy Type\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = insurance_clean,\n  x = policy_type,\n  y = profitability,\n  type = \"nonparametric\",\n  pairwise.comparisons = TRUE,\n  p.adjust.method = \"bonferroni\",\n  title = \"Profitability Distribution by Policy Type\"\n)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The Kruskal-Wallis test shows a statistically significant difference in profitability across policy types, p\\<0.001. Among the groups, COMP_N has the highest median profitability at approximately €405.38, followed by COMP_E at €306.63. In contrast, TP has the lowest median profitability at approximately €150.08, while CC and TPG show moderate median profitability values.\n\n=\\> This suggests that comprehensive policies, especially comprehensive policies without excess (COMP_N), tend to be more profitable in terms of median profitability. This may be because these policies generate higher premiums, which can offset claim costs. On the other hand, basic third-party policies (TP) appear less profitable, possibly because they have lower premium income while still being exposed to liability claims.\n\n=\\> However, although the effect size is larger than in some previous categorical comparisons, it is still relatively small. This means policy type has a statistically significant association with profitability, but it does not fully explain profitability variation. Extreme negative outliers are also present across several policy types, especially COMP_E, indicating that severe loss cases can occur even in generally profitable product groups.\n\n#### Power-to-Weight Ratio vs Profitability\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ncor_pwr <- cor(insurance_clean$power_to_weight_ratio, insurance_clean$profitability,\n               method = \"spearman\", use = \"complete.obs\")\n\ninsurance_clean %>%\n  sample_n(min(5000, nrow(insurance_clean))) %>%\n  ggplot(aes(x = power_to_weight_ratio, y = profitability)) +\n  geom_point(alpha = 0.25, color = \"purple\") +\n  geom_smooth(method = \"loess\", color = \"red\", se = TRUE) +\n  scale_y_continuous(labels = comma) +\n  labs(\n    title = \"Weight-to-Power Ratio vs Profitability\",\n    subtitle = paste0(\"Spearman correlation: \", round(cor_pwr, 3)),\n    x = \"Weight-to-Power Ratio (kg per horsepower)\",\n    y = \"Profitability (€)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The scatter plot shows a weak negative relationship between weight-to-power ratio and profitability. The Spearman correlation is -0.107, suggesting that vehicles with higher weight-to-power ratios tend to have slightly lower profitability. However, the relationship is weak, and most observations are clustered close to zero profitability. This means weight-to-power ratio alone does not strongly explain profitability variation.\n\n#### Total Exposure vs Profitability\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\ncor_exp <- cor(insurance_clean$total_exposure, insurance_clean$profitability,\n               method = \"spearman\", use = \"complete.obs\")\n\ninsurance_clean %>%\n  sample_n(min(5000, nrow(insurance_clean))) %>%\n  ggplot(aes(x = total_exposure, y = profitability)) +\n  geom_point(alpha = 0.25, color = \"orange\") +\n  geom_smooth(method = \"loess\", color = \"red\", se = TRUE) +\n  scale_y_continuous(labels = comma) +\n  labs(\n    title = \"Total Exposure vs Profitability\",\n    subtitle = paste0(\"Spearman correlation: \", round(cor_exp, 3)),\n    x = \"Total Exposure (years)\",\n    y = \"Profitability (€)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-51-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The scatter plot shows a moderate positive relationship between total_exposure and profitability, with a Spearman correlation of 0.565. This suggests that policies with longer exposure periods tend to have higher profitability. This is reasonable because higher exposure generally means the policy was active for longer, allowing more premium to be earned.\n\nHowever, total_exposure should be interpreted carefully because it is not a normal risk factor. It directly affects both premium earned and claim opportunity. Longer exposure can increase premium income, but it also gives more time for claims to occur. Therefore, the positive relationship may partly reflect the way profitability is constructed, rather than a pure risk effect.\n\n#### Raincloud Plot: Profitability by Area\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data for plotting only\nplot_data <- insurance_clean %>%\n  filter(profitability >= -2000, profitability <= 2000)\n\n# Sample points for cleaner display\nset.seed(123)\npoint_data <- plot_data %>%\n  group_by(circulation_area) %>%\n  slice_sample(n = 1500) %>%\n  ungroup()\n\n# Median values\nmedian_data <- plot_data %>%\n  group_by(circulation_area) %>%\n  summarise(\n    median_profit = median(profitability, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nggplot(plot_data, aes(x = circulation_area, y = profitability,\n                      fill = circulation_area, color = circulation_area)) +\n  \n  # Half-eye / half-violin density\n  stat_halfeye(\n    adjust = 0.7,\n    width = 0.6,\n    justification = -0.25,\n    .width = 0,\n    point_colour = NA,\n    alpha = 0.45\n  ) +\n  \n  # Boxplot in the middle\n  geom_boxplot(\n    width = 0.12,\n    outlier.shape = NA,\n    alpha = 0.5,\n    color = \"black\"\n  ) +\n  \n  # Sampled individual points\n  geom_jitter(\n    data = point_data,\n    width = 0.08,\n    alpha = 0.10,\n    size = 0.6,\n    show.legend = FALSE\n  ) +\n  \n  # Median point\n  geom_point(\n    data = median_data,\n    aes(x = circulation_area, y = median_profit),\n    inherit.aes = FALSE,\n    color = \"black\",\n    size = 2.5\n  ) +\n  \n  # Zero-profit line\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  \n  scale_y_continuous(labels = comma) +\n  labs(\n    title = \"Raincloud Plot: Profitability by Circulation Area\",\n    subtitle = \"Filtered to profitability between -€2,000 and €2,000 for readability\",\n    x = \"Circulation Area\",\n    y = \"Profitability (€)\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(\n    legend.position = \"none\",\n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** The raincloud plot compares profitability between circulation areas `R` and `U`. Both areas show similar profitability distributions, with most observations concentrated slightly above zero. Area `U` appears to have a slightly higher median profitability than area `R`, which is consistent with the earlier Mann-Whitney result. However, the difference is visually small, suggesting that circulation area has limited practical impact on profitability. Both groups also show negative profitability cases, indicating that loss-making policies exist in both regions.\n\nThis visual result is consistent with the Mann-Whitney test, which found a statistically significant difference between areas. However, the effect size was very small, so the difference is statistically detectable mainly because of the large sample size rather than because of a strong practical difference.\n\n### Factors Influencing Profitability\n\n#### Profitability Spread by Fuel Type: Median with Interquartile Range\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprofit_summary <- insurance_clean %>%\n  group_by(fuel_type) %>%\n  summarise(\n    n = n(),\n    median = median(profitability, na.rm = TRUE),\n    q1 = quantile(profitability, 0.25, na.rm = TRUE),\n    q3 = quantile(profitability, 0.75, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  filter(n > 1000)\n\nggplot(profit_summary) +\n  geom_errorbar(\n    aes(\n      x = reorder(fuel_type, median),\n      ymin = q1,\n      ymax = q3\n    ),\n    width = 0.2,\n    colour = \"black\"\n  ) +\n  geom_point(\n    aes(x = reorder(fuel_type, median), y = median),\n    color = \"red\",\n    size = 2\n  ) +\n  coord_flip() +\n  scale_y_continuous(labels = comma) +\n  labs(\n    title = \"Median Profitability by Fuel Type with Interquartile Range\",\n    subtitle = \"Error bars represent the 25th to 75th percentile range\",\n    x = \"Fuel Type\",\n    y = \"Median Profitability (€)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Since profitability is highly skewed and contains extreme outliers, median profitability with interquartile range is used instead of mean profitability with confidence intervals. The median provides a more robust measure of central tendency, while the IQR shows the spread of the middle 50% of observations. This approach is more consistent with the non-parametric tests used earlier.\n\n#### Claims Volatility Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvolatility_by_fuel <- insurance_clean %>%\n  filter(total_incurred > 0) %>%\n  group_by(fuel_type) %>%\n  summarise(\n    n = n(),\n    mean_claim = mean(total_incurred, na.rm = TRUE),\n    sd_claim = sd(total_incurred, na.rm = TRUE),\n    cv = sd_claim / mean_claim,\n    .groups = \"drop\"\n  ) %>%\n  filter(n > 100)\n\nggplot(volatility_by_fuel, aes(x = reorder(fuel_type, cv), y = cv, fill = fuel_type)) +\n  geom_col() +\n  geom_text(aes(label = round(cv, 2)), hjust = -0.2) +\n  coord_flip() +\n  scale_y_continuous(\n    labels = comma,\n    expand = expansion(mult = c(0, 0.15))\n  ) +\n  labs(\n    title = \"Claims Volatility by Fuel Type\",\n    subtitle = \"Coefficient of Variation (SD / Mean) - Positive claims only\",\n    x = \"Fuel Type\",\n    y = \"Coefficient of Variation\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Among policies with positive claims, claim cost volatility differs across fuel types. Gasoline (`G`) has the highest coefficient of variation, followed by diesel (`D`), indicating that claim amounts are more variable relative to their average for gasoline policies. This suggests greater unpredictability in claim severity for gasoline vehicles compared to diesel vehicles.\n\n#### Volatility by Geographic Area\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvolatility_by_area <- insurance_clean %>%\n  filter(total_incurred > 0) %>%\n  group_by(circulation_area) %>%\n  summarise(\n    n = n(),\n    mean_claim = mean(total_incurred, na.rm = TRUE),\n    sd_claim = sd(total_incurred, na.rm = TRUE),\n    cv = sd_claim / mean_claim,\n    .groups = \"drop\"\n  )\n\nggplot(volatility_by_area, aes(\n  x = reorder(circulation_area, cv),\n  y = cv,\n  fill = circulation_area\n)) +\n  geom_col() +\n  geom_text(aes(label = round(cv, 2)), hjust = -0.2) +\n  coord_flip() +\n  scale_y_continuous(\n    labels = comma,\n    expand = expansion(mult = c(0, 0.15))\n  ) +\n  labs(\n    title = \"Claims Volatility by Circulation Area\",\n    subtitle = \"Coefficient of Variation (SD / Mean) - Positive claims only\",\n    x = \"Area\",\n    y = \"Coefficient of Variation\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n:::\n\n\n**Interpretation:** Among policies with positive claims, claim cost volatility differs between circulation areas. Area `R` has a higher coefficient of variation than area `U`, indicating that claim amounts in area `R` are more variable relative to their average. This suggests that rural/regional areas may have less predictable claim severity compared to urban areas.\n\n### Key Findings\n\n**Univariate Insights:**\n\n- Premium is right-skewed, with most policies below €500 and a small number of high-premium outliers extending beyond €5,000.\n- Claim costs are highly zero-inflated — 88.1% of policies have no claims. Among those with claims, the distribution is strongly right-skewed, with a few extreme cases reaching nearly €600,000.\n- Profitability is generally positive for most policies, but the distribution has a long negative left tail driven by high-severity claims. The signed log transformation reveals two distinct clusters: a large profitable group and a smaller loss-making group.\n- Vehicle age is concentrated between 10–45 years, with relatively few new or very old vehicles. Driver age and driving experience are broadly distributed, with most policyholders in the 36–65 age range and 11–40 years of experience.\n- The portfolio is dominated by diesel vehicles (63.9%) and CC policy type (57.9%). Most policyholders have a good claims history (bonus score G).\n\n**Bivariate Insights:**\n\n- Premium and claim costs have only a weak positive relationship (Spearman ρ = 0.217), indicating that premium alone does not strongly predict claim cost.\n- Total exposure has the strongest positive relationship with profitability (Spearman ρ = 0.565), reflecting that longer-active policies earn more premium. This should be interpreted carefully as exposure directly affects how profitability is constructed.\n- Power-to-weight ratio shows a weak negative relationship with profitability (Spearman ρ = −0.107), suggesting higher-performance vehicles carry slightly more risk.\n- Policy type shows the most meaningful group difference: comprehensive policies (COMP_N, COMP_E) have higher median profitability than basic third-party policies (TP), likely due to higher premium income.\n- Bonus score shows a counterintuitive pattern — the B (poor claims history) group has the highest median profitability — but this group is very small and results should be interpreted cautiously.\n- Profitability differs significantly across fuel type, circulation area, vehicle age group, driver age group, driving experience group, and municipality type. However, effect sizes are consistently very small across all these variables, meaning no single factor strongly explains profitability variation.\n- Policies with claims have substantially lower profitability than those without, which is expected by construction. This confirms the importance of claim occurrence as a driver of loss, rather than being a new analytical insight.\n\n**Volatility Findings:**\n\n- Gasoline vehicles show the highest claim cost volatility (CV), followed by diesel, indicating greater unpredictability in claim amounts for these fuel types.\n- Area R has higher relative claim volatility than Area U, suggesting more dispersed or unpredictable claim costs in rural/regional areas.\n- CV values are high (\\>3) for all groups, reflecting the heavy-tailed nature of insurance claim distributions. These should be treated as relative comparisons between groups rather than absolute measures of risk.\n\n## Limitations\n\n### Multiple Testing\n\nThis analysis conducted numerous statistical tests (10+ bivariate comparisons) without applying a global family-wise error rate correction. While Bonferroni correction was applied within each `ggbetweenstats` analysis for pairwise comparisons, the overall multiple testing problem across all analyses was not addressed. This increases the risk of Type I errors (false positives). Readers should interpret p-values cautiously and focus on effect sizes and practical significance rather than statistical significance alone.\n\n### Small Sample Sizes\n\nSeveral subgroups have small sample sizes that limit the reliability of their results: - Driver age 18-25: Very small sample size compared to other age groups - Bonus score B and N: Only 1.3% and 2.2% of the portfolio respectively - Municipality type IS (Islands): Only 6.8% of observations - Policy type TP and COMP_N: 1.6% and 4.5% respectively - Driving experience 0-10 years: Only 15 observations\n\nResults for these groups should be interpreted with caution, as small samples can produce unstable estimates and may not be representative of the broader population.\n\n### Effect Size Interpretation\n\nThroughout the bivariate analysis, most statistically significant results showed very small effect sizes. This pattern is common in large datasets where even trivial differences become statistically significant. The practical importance of these findings should be evaluated based on effect sizes and business context rather than p-values alone.\n\n### Recommendations\n\n1.  **Policy Type Pricing:** Comprehensive policies (COMP_N, COMP_E) are more profitable than basic third-party policies. Review whether TP pricing adequately compensates for liability exposure.\n\n2.  **Claim Severity Management:** A small number of extreme claims drive most losses. Consider differentiated coverage terms, claim monitoring, or reinsurance for high-severity segments.\n\n3.  **Vehicle Age Risk:** Older vehicles (41–50 years, 50+) show wider negative profitability tails. Underwriting criteria for very old vehicles should reflect this higher downside risk.\n\n4.  **Geographic Volatility:** Area R shows higher claim volatility than Area U. Pricing and reserving assumptions should account for this regional disparity.\n\n5.  **Exposure-Adjusted Analysis:** Since total exposure strongly correlates with profitability by construction, future analysis should use exposure-adjusted metrics (e.g. profitability per unit exposure) for fairer segment comparisons.\n",
    "supporting": [
      "Take-home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}